### ISSUE TITLE
Add OntoUML tagged values 

### ISSUE THREAD

**Issue by claudenirmf** [OntoUML/ontouml-schema#6]
Add OntoUML tagged values as part of the schema. The following tagged values should be added to the `Class` objects:

* `isExtensional`: a boolean that represents the `isExtensional` property of classes decorated as «collection»
* `isPowertype`: a boolean that represents the `isPowertype` property of classes decorated as «type»
* `order`: a string that represents the `order` property of classes decorated as «type» (i.e., a number greater than "1" or "*")
* `nature`: an array of strings that represents the allowed `natures` able to instantiated the class. Natures are enumerated into `[ "object", "collection", "quantity", "relator", "mode", "quality", "event", "type" ]`.

**Comment by tgoprince** [comment]
Included in PR #7 .
